---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    tied: database
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bgg
      tied: database
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        tied: database
        name: bggdb-po
    spec:
      containers:
        - name: bggdb-container
          image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector:
    app: bgg
    tied: database
    name: bggdb-po
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  namespace: bggns
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: bggns
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

